import { sql } from "drizzle-orm";
import { integer, sqliteTable, text, index, unique } from "drizzle-orm/sqlite-core";

// ─── Users ────────────────────────────────────────────────────────────────────

/**
 * Application users. Each user maintains their own portfolio (watchlist)
 * of up to 10 companies and configures their own alert thresholds.
 */
export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  displayName: text("display_name").notNull(),
  /** Alert threshold: headcount drop percentage that triggers an alert. Range: 1–50. Default: 10. */
  headcountDropThreshold: integer("headcount_drop_threshold").notNull().default(10),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
});

// ─── Companies ────────────────────────────────────────────────────────────────

/**
 * Company directory. Pre-seeded via POST /api/admin/seed.
 * Coresignal fields are reserved for future API integration (not active in MVP).
 */
export const companies = sqliteTable("companies", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  /** Coresignal numeric company ID — used for headcount API lookups (future). */
  coresignalCompanyId: integer("coresignal_company_id"),
  /** Coresignal URL-safe company shorthand — alternative lookup key (future). */
  coresignalShorthand: text("coresignal_shorthand"),
  industry: text("industry").notNull().default(""),
  website: text("website").notNull().default(""),
  logoUrl: text("logo_url").notNull().default(""),
  /**
   * Logo cache lifecycle:
   * - "pending" — not yet fetched
   * - "ready"   — fetched and stored in R2 at key `pw/logos/{id}`
   * - "missing" — fetch attempted but no logo found
   */
  logoStatus: text("logo_status").$type<"pending" | "ready" | "missing">().notNull().default("pending"),
  /** Timestamp of the last logo fetch attempt (null if never attempted). */
  logoCheckedAt: integer("logo_checked_at", { mode: "timestamp" }),
  country: text("country").notNull().default(""),
  /** LinkedIn-style employee range string, e.g. "1001-5000". */
  employeeRange: text("employee_range").notNull().default(""),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
}, (t) => [
  index("companies_logo_status_idx").on(t.logoStatus),
]);

// ─── User Portfolio Companies ─────────────────────────────────────────────────

/**
 * Many-to-many join between users and companies.
 * Each user may watch at most 10 companies (enforced at API level).
 * Cascade-deletes when either side is removed.
 */
export const userPortfolioCompanies = sqliteTable(
  "user_portfolio_companies",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    companyId: text("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index("upc_user_idx").on(t.userId),
    index("upc_company_idx").on(t.companyId),
    unique("upc_user_company_uniq").on(t.userId, t.companyId),
  ],
);

// ─── Company Headcount Snapshots ──────────────────────────────────────────────

/**
 * Monthly employee count snapshots per company.
 * In the current MVP these are generated by the simulation engine.
 * Future: sourced from the Coresignal Historical Headcount API.
 *
 * One snapshot per company per month is enforced by the unique constraint.
 */
export const companyHeadcountSnapshots = sqliteTable(
  "company_headcount_snapshots",
  {
    id: text("id").primaryKey(),
    companyId: text("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    headcount: integer("headcount").notNull(),
    /** Month of the snapshot in "YYYY-MM" format, e.g. "2025-03". */
    recordedAt: text("recorded_at").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index("chs_company_idx").on(t.companyId),
    unique("chs_company_recorded_uniq").on(t.companyId, t.recordedAt),
  ],
);

// ─── Company News ─────────────────────────────────────────────────────────────

/**
 * News articles associated with a company.
 * In the current MVP these are generated by the simulation engine.
 * Future: sourced from NewsAPI with OpenAI sentiment scoring.
 */
export const companyNews = sqliteTable(
  "company_news",
  {
    id: text("id").primaryKey(),
    companyId: text("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    url: text("url").notNull().default(""),
    sourceName: text("source_name").notNull().default(""),
    /** ISO 8601 timestamp string, e.g. "2025-03-15T10:30:00Z". */
    publishedAt: text("published_at").notNull().default(""),
    /**
     * Negativity score from 0 to 100.
     * 0 = very positive, 50 = neutral, 100 = very negative.
     * Alert threshold: avgSentimentScore >= 70 triggers hasSentimentAlert.
     */
    sentimentScore: integer("sentiment_score").notNull().default(50),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index("cn_company_idx").on(t.companyId),
    index("cn_company_published_idx").on(t.companyId, t.publishedAt),
  ],
);

// ─── Company Notes ────────────────────────────────────────────────────────────

/**
 * Free-text notes written by a user about a specific company in their portfolio.
 * One note per user per company (upserted on write). Max 5000 characters (API-enforced).
 * Deleting a portfolio entry cascade-deletes its notes.
 */
export const companyNotes = sqliteTable(
  "company_notes",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    companyId: text("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    content: text("content").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    unique("cno_user_company_uniq").on(t.userId, t.companyId),
  ],
);

// ─── Types ────────────────────────────────────────────────────────────────────

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Company = typeof companies.$inferSelect;
export type NewCompany = typeof companies.$inferInsert;
export type UserPortfolioCompany = typeof userPortfolioCompanies.$inferSelect;
export type NewUserPortfolioCompany = typeof userPortfolioCompanies.$inferInsert;
export type CompanyHeadcountSnapshot = typeof companyHeadcountSnapshots.$inferSelect;
export type NewCompanyHeadcountSnapshot = typeof companyHeadcountSnapshots.$inferInsert;
export type CompanyNewsItem = typeof companyNews.$inferSelect;
export type NewCompanyNewsItem = typeof companyNews.$inferInsert;
export type CompanyNote = typeof companyNotes.$inferSelect;
export type NewCompanyNote = typeof companyNotes.$inferInsert;
